import React from 'react';
import { toPng } from 'html-to-image';
import { Copy, Check } from 'lucide-react';
import { cn } from '../lib/utils';

interface SvgCopyButtonProps {
  targetId: string;
  className?: string;
  label?: string;
}

export const SvgCopyButton: React.FC<SvgCopyButtonProps> = ({ targetId, className, label = "复制 SVG 到 Figma" }) => {
  const [copied, setCopied] = React.useState(false);

  const copyAsSvg = async (e: React.MouseEvent) => {
    e.stopPropagation();
    const element = document.getElementById(targetId);
    if (!element) return;

    try {
      // Figma has issues with foreignObject in SVGs generated by html-to-image.
      // A more reliable way for Figma is to generate a high-res PNG and wrap it in a clean SVG.
      
      // Temporarily ensure dimensions and styles for capture
      const originalStyle = element.style.cssText;
      element.style.width = '1440px';
      element.style.height = '960px';
      element.style.backgroundColor = '#ffffff';
      element.style.position = 'relative';
      element.style.zIndex = '9999';

      const dataUrl = await toPng(element, {
        backgroundColor: '#ffffff',
        width: 1440,
        height: 960,
        pixelRatio: 2, // High resolution for Figma
        cacheBust: true,
      });

      // Restore original style
      element.style.cssText = originalStyle;

      // Create a clean SVG wrapper with the image embedded
      // Using both href and xlink:href for maximum compatibility
      const svgContent = `
<svg width="1440" height="960" viewBox="0 0 1440 960" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <rect width="1440" height="960" fill="#ffffff"/>
  <image width="1440" height="960" href="${dataUrl}" xlink:href="${dataUrl}"/>
</svg>`.trim();

      // Fallback for clipboard
      if (navigator.clipboard && navigator.clipboard.writeText) {
        await navigator.clipboard.writeText(svgContent);
      } else {
        const textArea = document.createElement("textarea");
        textArea.value = svgContent;
        document.body.appendChild(textArea);
        textArea.select();
        document.execCommand('copy');
        document.body.removeChild(textArea);
      }

      setCopied(true);
      setTimeout(() => {
        setCopied(false);
      }, 2000);
    } catch (err) {
      console.error('Failed to copy SVG:', err);
      alert('复制失败，请重试');
    }
  };

  return (
    <button
      onClick={copyAsSvg}
      className={cn(
        "flex items-center gap-2 px-3 py-1.5 text-xs font-medium transition-all rounded-md border",
        copied 
          ? "bg-emerald-50 text-emerald-600 border-emerald-200" 
          : "bg-white text-slate-600 border-slate-200 hover:border-indigo-400 hover:text-indigo-600 shadow-sm",
        className
      )}
    >
      {copied ? <Check size={14} /> : <Copy size={14} />}
      {copied ? "已复制" : label}
    </button>
  );
};
